### ISSUE TITLE
Suggestion: Filter by rating

### ISSUE THREAD

**Issue by Joshfindit** [F4R4N/movie-quote#2]
Lot of adult quotes by default.
Even having a Movie/series rating would be helpful:

https://movie-quote-api.herokuapp.com/v1/18plus/quote/

_(Note: I'm not making any personal judgements. I fully support uncensored quotes, it's just one of those things that eventually comes up)_

**Comment by F4R4N** [comment]
thanks for your suggestion,
you are right about adult quotes. I take care of that (something like 18+ is good I guess).
