### ISSUE TITLE
Heroku app down

### ISSUE THREAD

**Issue by ssaunier** [F4R4N/movie-quote#9]
Hello @F4R4N,

Thanks for hosting this project! It seems that it is down at the moment:

<img width="933" alt="Screenshot 2022-04-28 at 12 48 29" src="https://user-images.githubusercontent.com/414418/165736505-b3a34611-4d50-4864-99c9-10a98ef34039.png">

Did you try `heroku restart` on it?

Thank you very much!

**Comment by F4R4N** [comment]
still have this problem?

**Comment by ssaunier** [comment]
All good 🙌
